#!/usr/bin/env node
// Scaffold a new theme submission for the StoryLark Gallery.
//
// Creates themes/<id>/brand.json + themes/<id>/theme.css with the full
// token contract (light + dark) filled in with neutral placeholder values,
// and prints a ready-to-paste public/registry.json entry.
//
// This does NOT touch the StoryLark engine repo or build anything — it only
// scaffolds the submission files this gallery repo's CONTRIBUTING.md asks
// for. To turn a real StoryLark brand into an installable package, use
// `npm run package-theme` in a checkout of github.com/StoryLark/storylark.
//
// Usage:
//   node scripts/new-theme.mjs <id> ["Display Name"] ["Author"]
//   node scripts/new-theme.mjs <id> --force   (overwrite an existing themes/<id>/)

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

function fail(msg) {
  console.error(`error: ${msg}`);
  process.exit(1);
}

const rawArgs = process.argv.slice(2);
const force = rawArgs.includes("--force");
const args = rawArgs.filter((a) => a !== "--force");

const [id, nameArg, authorArg] = args;

if (!id) {
  fail(
    "usage: node scripts/new-theme.mjs <id> [\"Display Name\"] [\"Author\"] [--force]"
  );
}
if (!/^[a-z][a-z0-9-]*$/.test(id)) {
  fail(`id "${id}" must be kebab-case (lowercase letters, digits, hyphens), starting with a letter`);
}

const name = nameArg || id.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
const author = authorArg || "Your name or project";

const outDir = join(process.cwd(), "themes", id);
if (existsSync(outDir) && !force) {
  fail(`themes/${id}/ already exists. Pass --force to overwrite.`);
}
mkdirSync(outDir, { recursive: true });

// Neutral placeholder palette. Meant to be immediately retuned — the point
// is a syntactically and structurally complete starting point that already
// satisfies CONTRIBUTING.md's "full token contract, both light and dark"
// check, not a finished look.
const brandJson = {
  contractVersion: 1,
  id,
  name,
  appName: name,
  shortName: name,
  tagline: "One sentence: what this library is for.",
  author,
  themeColor: "#F5F4F2",
  backgroundColor: "#F5F4F2",
  defaultTheme: "light",
  fonts: {
    display: "Newsreader",
    headers: "Newsreader",
    body: "Newsreader",
    mono: "Inter",
  },
};

const themeCss = `/* ${name} — starter theme, generated by scripts/new-theme.mjs.
 * Retune every value below; keep the token names. Both light and dark
 * modes must stay complete — see docs/build-your-own-theme.md in the
 * StoryLark engine repo for what each token is for.
 */
:root {
  color-scheme: light;

  --bg: #F5F4F2;
  --bg-raised: #FFFFFF;
  --bg-sunken: #E8E6E1;
  --text: #232323;
  --text-muted: #63605A;
  --text-faint: #A39F96;
  --accent: #3B6E64;
  --accent-strong: #2A4F47;
  --rule: #DEDAD1;
  --link: #3B6E64;

  --font-display: "Newsreader", Georgia, serif;
  --font-headers: "Newsreader", Georgia, serif;
  --font-body: "Newsreader", Georgia, serif;
  --font-mono: "Inter", system-ui, sans-serif;

  --highlight-word: rgba(224, 164, 35, 0.22);
  --highlight-block: rgba(224, 164, 35, 0.5);
}

:root[data-theme="dark"] {
  color-scheme: dark;

  --bg: #17181A;
  --bg-raised: #202225;
  --bg-sunken: #0F1011;
  --text: #F0EEEA;
  --text-muted: #B3AFA6;
  --text-faint: #78746C;
  --accent: #5FA89A;
  --accent-strong: #7FC3B5;
  --rule: #2C2E31;
  --link: #7FC3B5;

  --highlight-word: rgba(240, 190, 80, 0.26);
  --highlight-block: rgba(240, 190, 80, 0.5);
}
`;

writeFileSync(join(outDir, "brand.json"), JSON.stringify(brandJson, null, 2) + "\n");
writeFileSync(join(outDir, "theme.css"), themeCss);

const registryEntry = {
  id,
  name,
  author,
  description: "One or two sentences: the mood, the key colors, what makes it distinct.",
  swatches: ["#F5F4F2", "#3B6E64", "#E0A423", "#232323"],
  fonts: "Newsreader · Inter",
  source: `https://github.com/StoryLark/gallery/tree/main/themes/${id}`,
  install:
    "Import as a package: run `npm run package-theme` against this brand in a StoryLark checkout, then install it from the admin portal's Brand & themes card or `npm run import-theme`.",
};

console.log(`Created:`);
console.log(`  themes/${id}/brand.json`);
console.log(`  themes/${id}/theme.css`);
console.log();
console.log(`Next steps:`);
console.log(`  1. Retune the tokens in themes/${id}/theme.css and the fields in`);
console.log(`     themes/${id}/brand.json to your theme's actual look.`);
console.log(`  2. Paste this into public/registry.json under "themes" (adjust the`);
console.log(`     placeholder swatches/description/fonts to match your real values):`);
console.log();
console.log(
  JSON.stringify(registryEntry, null, 2)
    .split("\n")
    .map((l) => "    " + l)
    .join("\n")
);
console.log();
console.log(`  3. See CONTRIBUTING.md for the full submission + review process.`);
